package GUI;

import java.awt.BorderLayout;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author gihanpunarji
 */
public class StockAnalyze extends javax.swing.JFrame {

    /**
     * Creates new form StockAnalyze
     */
    public StockAnalyze() {
        initComponents();
        addPieChartToPanel3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
    // Stock Chart
    private void addPieChartToPanel3() {
        PieDataset stockDataset = createDataset();
        JFreeChart chart = createChart(stockDataset);
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(340, 220)); // Adjust size to fit jPanel3

        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(chartPanel, BorderLayout.CENTER);
        jPanel1.validate();
    }
    

    private PieDataset createDataset() {
        DefaultPieDataset stockDataset = new DefaultPieDataset();
        stockDataset.setValue("Ingrediant1", 40);
        stockDataset.setValue("Ingrediant2", 30);
        stockDataset.setValue("Ingrediant3", 30);
        return stockDataset;
    }

    private JFreeChart createChart(PieDataset stockDataset) {
        return ChartFactory.createPieChart(
                "Total Stock",  
                stockDataset,            
                true,                
                true,
                false);
    }
    
    // Stock Chart

}
